services:
  postgres:
    image: postgres:16
    container_name: pulse-db # Name of the container for easy reference
    environment:
      POSTGRES_USER: ${DATABASE_USER} # Database user
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD} # Database password
      POSTGRES_DB: ${DATABASE_NAME} # The name of the database to create on start
    ports:
      - '3002:5432' # Expose port 5432 for local access to the database
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data between restarts
    restart: always # Ensure the container restarts automatically if it crashes

volumes:
  postgres_data:
    driver: local # Use a named volume to persist data locally
